services:
  cb_ethgas_deposit:
    image: ghcr.io/ethgas-developer/commitboost_ethgas_deposit:v1.0.0-beta.4
    container_name: cb_ethgas_deposit
    environment:
      CB_MODULE_ID: ETHGAS_DEPOSIT
      CB_CONFIG: /cb-config.toml
      CB_SIGNER_URL: http://localhost:20000 # placeholder value
      CB_LOGS_DIR: /var/logs/commit-boost
    volumes:
    - ./config.toml:/cb-config.toml:ro
    - ./logs/ethgas_deposit:/var/logs/commit-boost
    env_file: .cb.env
