name: Build and Push Multi-Platform Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get the version
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ethgas-developer
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Multi-Platform Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/ethgas-developer/${{ inputs.image_name }}:latest
          ghcr.io/ethgas-developer/${{ inputs.image_name }}:${{ steps.get_version.outputs.version }}
        cache-from: type=registry,ref=ghcr.io/ethgas-developer/${{ inputs.image_name }}:buildcache
        cache-to: type=registry,ref=ghcr.io/ethgas-developer/${{ inputs.image_name }}:buildcache,mode=max
